/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as UsersRouteImport } from './routes/users';
import { Route as ServicesRouteImport } from './routes/services';
import { Route as RolesRouteImport } from './routes/roles';
import { Route as ProductsRouteImport } from './routes/products';
import { Route as PermissionsRouteImport } from './routes/permissions';
import { Route as PackagesRouteImport } from './routes/packages';
import { Route as LoginRouteImport } from './routes/login';
import { Route as CategoriesRouteImport } from './routes/categories';
import { Route as AlbumsRouteImport } from './routes/albums';
import { Route as IndexRouteImport } from './routes/index';

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any);
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any);
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any);
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any);
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any);
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/albums': typeof AlbumsRoute;
  '/categories': typeof CategoriesRoute;
  '/login': typeof LoginRoute;
  '/packages': typeof PackagesRoute;
  '/permissions': typeof PermissionsRoute;
  '/products': typeof ProductsRoute;
  '/roles': typeof RolesRoute;
  '/services': typeof ServicesRoute;
  '/users': typeof UsersRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/albums': typeof AlbumsRoute;
  '/categories': typeof CategoriesRoute;
  '/login': typeof LoginRoute;
  '/packages': typeof PackagesRoute;
  '/permissions': typeof PermissionsRoute;
  '/products': typeof ProductsRoute;
  '/roles': typeof RolesRoute;
  '/services': typeof ServicesRoute;
  '/users': typeof UsersRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/albums': typeof AlbumsRoute;
  '/categories': typeof CategoriesRoute;
  '/login': typeof LoginRoute;
  '/packages': typeof PackagesRoute;
  '/permissions': typeof PermissionsRoute;
  '/products': typeof ProductsRoute;
  '/roles': typeof RolesRoute;
  '/services': typeof ServicesRoute;
  '/users': typeof UsersRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/albums'
    | '/categories'
    | '/login'
    | '/packages'
    | '/permissions'
    | '/products'
    | '/roles'
    | '/services'
    | '/users';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/albums'
    | '/categories'
    | '/login'
    | '/packages'
    | '/permissions'
    | '/products'
    | '/roles'
    | '/services'
    | '/users';
  id:
    | '__root__'
    | '/'
    | '/albums'
    | '/categories'
    | '/login'
    | '/packages'
    | '/permissions'
    | '/products'
    | '/roles'
    | '/services'
    | '/users';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AlbumsRoute: typeof AlbumsRoute;
  CategoriesRoute: typeof CategoriesRoute;
  LoginRoute: typeof LoginRoute;
  PackagesRoute: typeof PackagesRoute;
  PermissionsRoute: typeof PermissionsRoute;
  ProductsRoute: typeof ProductsRoute;
  RolesRoute: typeof RolesRoute;
  ServicesRoute: typeof ServicesRoute;
  UsersRoute: typeof UsersRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users';
      path: '/users';
      fullPath: '/users';
      preLoaderRoute: typeof UsersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/services': {
      id: '/services';
      path: '/services';
      fullPath: '/services';
      preLoaderRoute: typeof ServicesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/roles': {
      id: '/roles';
      path: '/roles';
      fullPath: '/roles';
      preLoaderRoute: typeof RolesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/products': {
      id: '/products';
      path: '/products';
      fullPath: '/products';
      preLoaderRoute: typeof ProductsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/permissions': {
      id: '/permissions';
      path: '/permissions';
      fullPath: '/permissions';
      preLoaderRoute: typeof PermissionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/packages': {
      id: '/packages';
      path: '/packages';
      fullPath: '/packages';
      preLoaderRoute: typeof PackagesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/categories': {
      id: '/categories';
      path: '/categories';
      fullPath: '/categories';
      preLoaderRoute: typeof CategoriesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/albums': {
      id: '/albums';
      path: '/albums';
      fullPath: '/albums';
      preLoaderRoute: typeof AlbumsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRoute: AlbumsRoute,
  CategoriesRoute: CategoriesRoute,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRoute,
  PermissionsRoute: PermissionsRoute,
  ProductsRoute: ProductsRoute,
  RolesRoute: RolesRoute,
  ServicesRoute: ServicesRoute,
  UsersRoute: UsersRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
